version: '3.3'

volumes:
  server_node_modules:
  fe_static:

services:
  server:
    container_name: server
    restart: always
    build:
      context: .
      dockerfile: Dockerfile_server
    volumes:
      - ./server:/server
      - server_node_modules:/server/node_modules
    expose:
      - "3001"
    environment:
      - PORT=3001

  fe-build:
    container_name: fe-build
    restart: "no"
    build:
      context: .
      dockerfile: Dockerfile_fe_build
    volumes:
      - fe_static:/build_app/dist